version: '3.9'

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=testa
      - DB_USER=roott
      - DB_PASS=my-secret-pw

volumes:
  mysql_data:
