# Generated by Django 5.0.6 on 2024-06-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_date_joined_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='output',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.problem'),
        ),
    ]
